Adds archive package
m-lab/disco pull request #2
Opened 2020-06-16 16:51 UTC by nkinkade

The archive package defines the JSON model for archives, the names and paths of archives, and the actual writing of archives to disk.

Also adds Coveralls.io markdown to README.md, and adds a newline at end of cloudbuild.yaml.

2020-06-16 17:39 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[archive/archive.go, line 33 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9y67-X5EOKqXEve4Vr:-M9y67-X5EOKqXEve4Vs:b9g5gvn) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive.go#L33)):*
> ```Go
> 	data, err := json.MarshalIndent(m, "", "    ")
> 	rtx.Must(err, "ERROR: failed to marshal archive.Model to JSON. This should never happen")
> 	return data, err
> ```

I suggest calling this function `MustMarshalJSON` that only returns the `[]byte` array. The `rtx.Must` makes the returned error value unnecessary.
___
*[archive/archive.go, line 43 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9y6dC6DVvoS8rrdQom:-M9y6dC6DVvoS8rrdQon:byshsr0) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive.go#L43)):*
> ```Go
> 	// Calculate the start time, which will be Now() - interval, and then format
> 	// the archive file name based on the calculated values.
> 	startTime := now.Add(time.Duration(interval) * -time.Second)
> ```

The relative times here worry me.

The start and end time should be absolute "book ends" on the times contained in the archived metrics. I suggest renaming `now` to `start` to prevent confusion with `time.Now()` which is what I though as I read the comment here also.

Is there any way to track the absolute "start" and "end" times within the metrics collected so they could be passed in here explicitly rather than calculated using relative offsets? This could be private fields that aren't exported as JSON, or that are explicitly annotated to be ignored by JSON.

Can we build things so that the signatures of this function is:

```
func GetPath(start time.Time, end time.Time, hostname string) string {
```

The goal being that the times strictly match the samples contained within.
___
*[archive/archive_test.go, line 131 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9yB6bt-IadgtPU8djW:-M9yB6bt-IadgtPU8djX:bcw5bbu) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive_test.go#L131)):*
> ```Go
> 	defer os.RemoveAll(dir)
> 
> 	jsonData, err := GetJSON(testModel)
> ```

`err` is not checked, but hopefully it can go away.


<!-- Sent from Reviewable.io -->

2020-06-16 18:43 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[archive/archive.go, line 33 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9y67-X5EOKqXEve4Vr:-M9yFCch8sv7a6_-vFZk:b7jmyuo) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive.go#L33)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest calling this function `MustMarshalJSON` that only returns the `[]byte` array. The `rtx.Must` makes the returned error value unnecessary.
</blockquote></details>

Good catch. Done. When I added the `rtx.Must()` call I forgot/failed to remove the `error` return part.
___
*[archive/archive.go, line 43 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9y6dC6DVvoS8rrdQom:-M9yN-i56lyNjzcydy6Y:b-4qm6vy) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The relative times here worry me.

The start and end time should be absolute "book ends" on the times contained in the archived metrics. I suggest renaming `now` to `start` to prevent confusion with `time.Now()` which is what I though as I read the comment here also.

Is there any way to track the absolute "start" and "end" times within the metrics collected so they could be passed in here explicitly rather than calculated using relative offsets? This could be private fields that aren't exported as JSON, or that are explicitly annotated to be ignored by JSON.

Can we build things so that the signatures of this function is:

```
func GetPath(start time.Time, end time.Time, hostname string) string {
```

The goal being that the times strictly match the samples contained within.
</blockquote></details>

In the current code the "start" and "end" times are _only_ used for the purposes of naming the archive file. They don't affect any of the underlying timestamps in the data. Does the parser somehow parse the filename into some meaningful fields in the table? I glanced through [what I think is the parser for DISCO](https://github.com/m-lab/etl/blob/master/parser/disco.go) and couldn't immediately see that the filename was used for anything.

Assuming the filename is somehow important, could we clarify what we mean by "absolute" start and end? It seems there are a few possible definitions of start (within some millisecond (microsecond?) range):

* When the call to `Collect()` is made.
* When the call to `Get()` is made.
* When the call to `Get()` returns.
* The 10 second window prior to `Write()` being called.

... and few possible meanings of "end":

* When the call to `Get()` returns.
* When the call to `Write()` is made.
* One of the possible values for "start" + 10s

In the code right now, the timestamp associated with each sample is roughly the time when the call to `Get()` returns. If I've understood correctly, we would like to have two timestamps in each sample, one indicating when `Collect()` was called, and the other indicating when `Get()` returns, so that we can calculate latencies for SNMP calls to be sure that our samples fall within the expected windows. Is this accurate?
___
*[archive/archive_test.go, line 131 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9yB6bt-IadgtPU8djW:-M9yFdW81RJXuQpRzODf:bss4a2b) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive_test.go#L131)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`err` is not checked, but hopefully it can go away.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2020-06-16 18:55 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[archive/archive.go, line 43 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9y6dC6DVvoS8rrdQom:-M9ySLMLCIVdJxzwZMNK:b-k9f58o) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive.go#L43)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

In the current code the "start" and "end" times are _only_ used for the purposes of naming the archive file. They don't affect any of the underlying timestamps in the data. Does the parser somehow parse the filename into some meaningful fields in the table? I glanced through [what I think is the parser for DISCO](https://github.com/m-lab/etl/blob/master/parser/disco.go) and couldn't immediately see that the filename was used for anything.

Assuming the filename is somehow important, could we clarify what we mean by "absolute" start and end? It seems there are a few possible definitions of start (within some millisecond (microsecond?) range):

* When the call to `Collect()` is made.
* When the call to `Get()` is made.
* When the call to `Get()` returns.
* The 10 second window prior to `Write()` being called.

... and few possible meanings of "end":

* When the call to `Get()` returns.
* When the call to `Write()` is made.
* One of the possible values for "start" + 10s

In the code right now, the timestamp associated with each sample is roughly the time when the call to `Get()` returns. If I've understood correctly, we would like to have two timestamps in each sample, one indicating when `Collect()` was called, and the other indicating when `Get()` returns, so that we can calculate latencies for SNMP calls to be sure that our samples fall within the expected windows. Is this accurate?


</blockquote></details>

The parser does not depend on the file names. When manually inspecting these files it is a great help. Today archives contain ~24 files (one per hour). The working changes will create 100's. I suspect precise filenames will come into play with bigquery also.

```
start time == min(sample.timestamp)
end time == max(sample.timestamp)
```

My main feedback is that we don't want to create new timestamps for the file name. We have all the timestamps available in the current data.

In my mind, this request is independent of the discussion about archiving precise collection times.


<!-- Sent from Reviewable.io -->

2020-06-17 18:09 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[archive/archive.go, line 43 at r1](https://reviewable.io/reviews/m-lab/disco/2#-M9y6dC6DVvoS8rrdQom:-MA2TDdKDaQlUCRLa1xX:b-fmpvjs) ([raw file](https://github.com/m-lab/disco/blob/0168901cc350d74b4ae38dede9622db24417c0de/archive/archive.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The parser does not depend on the file names. When manually inspecting these files it is a great help. Today archives contain ~24 files (one per hour). The working changes will create 100's. I suspect precise filenames will come into play with bigquery also.

```
start time == min(sample.timestamp)
end time == max(sample.timestamp)
```

My main feedback is that we don't want to create new timestamps for the file name. We have all the timestamps available in the current data.

In my mind, this request is independent of the discussion about archiving precise collection times.
</blockquote></details>

@stephen-soltesz: I believe this done. PTAL?


<!-- Sent from Reviewable.io -->

2020-06-17 18:22 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2#-:-MA2W1NF6PeAEQShZxvl:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[archive/archive.go, line 18 at r3](https://reviewable.io/reviews/m-lab/disco/2#-MA2Viqn0MbhlIEVvKrh:-MA2Viqn0MbhlIEVvKri:b-q3flyd) ([raw file](https://github.com/m-lab/disco/blob/5bedb06756971f6359d794dce4bc339cc9228a55/archive/archive.go#L18)):*
> ```Go
> type Sample struct {
> 	Timestamp    int64  `json:"timestamp"`
> 	CollectStart int64  `json:"collectstart"`
> ```

Hmm, I think you've done the right thing with the current schema. I'm just observing that there are multiple samples per collection, right?


<!-- Sent from Reviewable.io -->

2020-06-17 18:56 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[archive/archive.go, line 18 at r3](https://reviewable.io/reviews/m-lab/disco/2#-MA2Viqn0MbhlIEVvKrh:-MA2cjIq20Aiqn4U3RHl:b5hf5pv) ([raw file](https://github.com/m-lab/disco/blob/5bedb06756971f6359d794dce4bc339cc9228a55/archive/archive.go#L18)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, I think you've done the right thing with the current schema. I'm just observing that there are multiple samples per collection, right?
</blockquote></details>

That's right. For each write interval, for each metric, there will be multiple samples. Are you just verifying, or is there some possible concern in your question?


<!-- Sent from Reviewable.io -->

2020-06-17 19:06 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[archive/archive.go, line 18 at r3](https://reviewable.io/reviews/m-lab/disco/2#-MA2Viqn0MbhlIEVvKrh:-MA2f-CT7x5VDuRuQAH4:b-t6dz90) ([raw file](https://github.com/m-lab/disco/blob/5bedb06756971f6359d794dce4bc339cc9228a55/archive/archive.go#L18)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

That's right. For each write interval, for each metric, there will be multiple samples. Are you just verifying, or is there some possible concern in your question?
</blockquote></details>

I just verified in the open VC that the concern is data duplication/redundancy, but that this is probably good enough for now.


<!-- Sent from Reviewable.io -->

2020-06-17 19:06 UTC, merged