Adds 'main' and 'metrics' packages.
m-lab/disco pull request #3
Opened 2020-06-17 19:12 UTC by nkinkade

This is the final PR in this series of PRs, the result of which represents all of the current work done on DISCOv2.

2020-06-17 20:43 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[disco.go, line 97 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2hBno5iE1fErVgfRC:-MA2hBno5iE1fErVgfRD:b-igszyt) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/disco.go#L97)):*
> ```Go
> 			metrics.CollectStart = time.Now()
> 			metrics.Collect(client, config)
> 		}
> ```

I suggest additionally selecting on `<-mainCtx.Done()` with a `break` so that the loop can be broken.

See this hint https://stackoverflow.com/questions/25469682/break-out-of-select-loop
___
*[metrics/metrics.go, line 46 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2v3YrDK5gK6GckBul:-MA2v3YrDK5gK6GckBum:bqyag58) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L46)):*
> ```Go
> // getIfaces uses an ifAlias value to determine the logical interface number and
> // description for the machine's interface and the switch's uplink.
> func getIfaces(snmp snmp.SNMP, machine string) map[string]map[string]string {
> ```

Please do not alias package names with variable names. It makes it much harder to tell what's going on. Also, I'm sorry I didn't notice the naming of `snmp.SNMP` that's a mistake because it stutters. 

What if the snmp interface were named `snmp.Client` and the implementation were called `snmp.SwitchClient`? Then the parameter name could be simply `client`.
___
*[metrics/metrics.go, line 48 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2w3UJ6JI3qJIDOO0c:-MA2w3UJ6JI3qJIDOO0d:b-cdoc1u) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L48)):*
> ```Go
> func getIfaces(snmp snmp.SNMP, machine string) map[string]map[string]string {
> 	pdus, err := snmp.BulkWalkAll(ifAliasOid)
> 	rtx.Must(err, "Failed to walk the ifAlias OID")
> ```

Did I suggest this? It seems like a mistake. I can imagine times when the switch is reset or misconfigured and the bulkwalk would fail. Do we want the process to exit in that case? Or, is this something that can only happen once on start up? if so, that may be okay -- I suggest renaming the function to something like `mustGetIfaces()`.
___
*[metrics/metrics.go, line 104 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2xjs0CeuoZMC_R6Lz:-MA2xjs0CeuoZMC_R6M-:b-b9n6tv) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L104)):*
> ```Go
> func getOidsInt64(snmp snmp.SNMP, oids []string) (map[string]uint64, error) {
> 	oidMap := make(map[string]uint64)
> 	result, err := snmp.Get(oids)
> ```

This err is not used? Or it's used oddly. Please clarify or revise.
___
*[metrics/metrics.go, line 120 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2xeMT0cMQZV-mj4LH:-MA2xeMT0cMQZV-mj4LI:b-dw9gq3) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L120)):*
> ```Go
> 		}
> 	}
> 	return oidMap, err
> ```

Can `err` here be non-nil?
___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA30Dpi1TX9XPtnTkC5:b-1nm44r) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
> ```Go
> 			},
> 			[]string{
> 				"node",
> ```

Can we call this machine?


<!-- Sent from Reviewable.io -->

2020-06-17 21:48 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[disco.go, line 97 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2hBno5iE1fErVgfRC:-MA37Ys9EpRhxcTseAdX:b-896fix) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/disco.go#L97)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest additionally selecting on `<-mainCtx.Done()` with a `break` so that the loop can be broken.

See this hint https://stackoverflow.com/questions/25469682/break-out-of-select-loop
</blockquote></details>

Done.
___
*[metrics/metrics.go, line 46 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2v3YrDK5gK6GckBul:-MA39vmb89zJpu-_NxQa:b-896fix) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L46)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please do not alias package names with variable names. It makes it much harder to tell what's going on. Also, I'm sorry I didn't notice the naming of `snmp.SNMP` that's a mistake because it stutters. 

What if the snmp interface were named `snmp.Client` and the implementation were called `snmp.SwitchClient`? Then the parameter name could be simply `client`.
</blockquote></details>

Done.
___
*[metrics/metrics.go, line 48 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2w3UJ6JI3qJIDOO0c:-MA3AFQPEIFpPW2BnPs_:b-tty1dj) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Did I suggest this? It seems like a mistake. I can imagine times when the switch is reset or misconfigured and the bulkwalk would fail. Do we want the process to exit in that case? Or, is this something that can only happen once on start up? if so, that may be okay -- I suggest renaming the function to something like `mustGetIfaces()`.
</blockquote></details>

Done. `mustGetIfaces()` only gets run a single time when on startup. I suppose a failure could happen during starting, but in such a case the kubelet should just try to restart it. Rather than trying to add retry logic  to the code  would it be acceptable to just reuse the kubelets retry logic?
___
*[metrics/metrics.go, line 104 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2xjs0CeuoZMC_R6Lz:-MA3Bs4N9jA-lWxlGa2X:b-ukz9yg) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L104)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This err is not used? Or it's used oddly. Please clarify or revise.
</blockquote></details>

This was a mistake on my part. I observed once that `result` was nil when I accidentally specified some invalid list of OIDs, but because I wasn't checking to see that `err` was nil or not, I falsely assumed that it was possible or `Get()` to return a nil result, and so checked for it. More likely is that `Get()` returned a nil `result` with a non-nil `err`, which I just failed to check. I changed this to check `err` instead.
___
*[metrics/metrics.go, line 120 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2xeMT0cMQZV-mj4LH:-MA3CPlp7z6tzZGyEqun:b-tx22hq) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L120)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can `err` here be non-nil?
</blockquote></details>

You're right, it can't. I've changed it to nil.
___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA3C_KUDaOA3vfaRfNe:br0s3h9) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can we call this machine?
</blockquote></details>

I purposely picked the name `node`. `node` seems to be the label that k8s uses by default. The fact that we use `machine` instead has caused us to have to bend over backward so that auto-discovered metrics can be joined with our other metrics. Just a few examples that come to mind immediately:

https://github.com/m-lab/github-maintenance-exporter/blob/master/maintenancestate/state.go#L83
https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/prometheus.yml.template#L364
https://github.com/m-lab/k8s-support/blob/master/config/prometheus/prometheus.yml#L86

I would love to see a day when we no longer use the label `machine` and instead use only `node` everywhere to avoid things like the above. I don't want to perpetuate this node/machine disjunct, and was hoping that at the very least all new code could use "node", and then at some point the future we could start migrating all references of "machine" to "node.

Do you disagree with this?


<!-- Sent from Reviewable.io -->

2020-06-18 00:03 UTC, stephen-soltesz requested changes
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[disco.go, line 23 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3a_T5AtXP0r4hgf0n:-MA3a_T5AtXP0r4hgf0o:b-r37xiw) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/disco.go#L23)):*
> ```Go
> 	fListenAddress      = flag.String("listen-address", ":8888", "Address to listen on for telemetry.")
> 	fMetricsFile        = flag.String("metrics", "", "Path to YAML file defining metrics to scrape.")
> 	fWriteInterval      = flag.Uint64("write-interval", 300, "Interval in seconds to write out JSON files.")
> ```

Could this be a flag.Duration type? https://golang.org/pkg/flag/#Duration
___
*[metrics/metrics.go, line 48 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA2w3UJ6JI3qJIDOO0c:-MA3POXBEm5hKMs3IUSH:b-v8i7cn) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L48)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done. `mustGetIfaces()` only gets run a single time when on startup. I suppose a failure could happen during starting, but in such a case the kubelet should just try to restart it. Rather than trying to add retry logic  to the code  would it be acceptable to just reuse the kubelets retry logic?
</blockquote></details>

Yeah, I think so. I only saw that this was called once later in the review. :+1:
___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA3PwKTEmPW_uOHtq6b:bm1gg9y) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I purposely picked the name `node`. `node` seems to be the label that k8s uses by default. The fact that we use `machine` instead has caused us to have to bend over backward so that auto-discovered metrics can be joined with our other metrics. Just a few examples that come to mind immediately:

https://github.com/m-lab/github-maintenance-exporter/blob/master/maintenancestate/state.go#L83
https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/prometheus.yml.template#L364
https://github.com/m-lab/k8s-support/blob/master/config/prometheus/prometheus.yml#L86

I would love to see a day when we no longer use the label `machine` and instead use only `node` everywhere to avoid things like the above. I don't want to perpetuate this node/machine disjunct, and was hoping that at the very least all new code could use "node", and then at some point the future we could start migrating all references of "machine" to "node.

Do you disagree with this?
</blockquote></details>

Standardizing on one thing would be very welcome. It doesn't matter which one as long as the choice makes our lives easier.
___
*[metrics/metrics.go, line 41 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3cXOn2UC8h3ZEr1H5:-MA3cXOn2UC8h3ZEr1H6:b1c3wzg) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L41)):*
> ```Go
> 	scope          string
> 	ifDescr        string
> 	intervalSeries archive.Model
> ```

nit: why is this field named `intervalSeries`? is there a shorter name?
___
*[metrics/metrics.go, line 149 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3QTFX4L3pAwbguba7:-MA3QTFX4L3pAwbguba8:b-v3s7dt) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L149)):*
> ```Go
> 		return err
> 	}
> 	collectEnd := time.Now()
> ```

For another TODO, it would be worth while collecting a prometheus metric for the collect time as well. Probably a histogram.
___
*[metrics/metrics.go, line 152 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3TzIrCyejiD8NfbSu:-MA3TzIrCyejiD8NfbSv:bw362ts) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L152)):*
> ```Go
> 
> 	for oid, value := range oidValueMap {
> 		// This is less than ideal. Because we can't write to a map in a struct
> ```

I think I understand what the problem is.

The `metrics.oid` type is `map[string]oid` The value type is a struct literal. When getting a value from a map or returned from a function, the value is a _copy_. So, if you've observed that this doesn't work:

```
metrics.oids[oid].previousValue = value
```

It's because `previousValue` is being assigned to a temporary copy of the struct returned by the map lookup. 

To solve this, you can make the type a `map[string]*oid`. And, in `New` create the oid just as you're doing, but assign the `&oid{...}`. The return value of the map will still be a copy of the pointer, but because Go dereferences the pointer, there is only one version of the actual struct that the "pointer copy" points to. And, the assignment expression above should wai.
___
*[metrics/metrics.go, line 160 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3hW0h32rJi-5PmoUz:-MA3hW0h32rJi-5PmoV-:bkeyqr5) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L160)):*
> ```Go
> 		// If this is the first run then we have no previousValue with which to
> 		// calculate an increase, so we just record a previousValue and return.
> 		if metrics.firstRun == true {
> ```

Because this is a bool, you can use variable without the comparison, (same below) i.e.

```
if metrics.firstRun {
  ...
}
```
___
*[metrics/metrics.go, line 198 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3e7b5C9mlxbrlNHWl:-MA3e7b5C9mlxbrlNHWm:bg1nsp9) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L198)):*
> ```Go
> 	for oid, values := range metrics.oids {
> 		data := archive.MustMarshalJSON(values.intervalSeries)
> 		jsonData = append(jsonData, data...)
> ```

Does this add newlines between values? I'm also wondering whether `MustMarshalJSON` should use `MarshalIndent` rather than just `Marshal`? Don't do anything in this PR. This could be part of an "integration review".
___
*[metrics/metrics.go, line 200 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3V0YXCfzYF9Mx6TR6:-MA3V0YYDQEaJSEVcWzp:bxt4dvy) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L200)):*
> ```Go
> 		jsonData = append(jsonData, data...)
> 
> 		// This is less than ideal. Because we can't write to a map in a struct
> ```

If the `metrics.oids` type is updated, this should solve this issue too.

Please add a comment that this is resetting the samples.
___
*[metrics/metrics_test.go, line 396 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3j3J29kkYjZZCwRPj:-MA3j3J29kkYjZZCwRPk:b-mir9q6) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics_test.go#L396)):*
> ```Go
> 	rtx.Must(err, "Could not read test archive directory")
> 
> 	if len(a) != 1 {
> ```

Is it possible to check the file contents?


<!-- Sent from Reviewable.io -->

2020-06-18 03:52 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[disco.go, line 23 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3a_T5AtXP0r4hgf0n:-MA4Iomn72fuDqO-C4o4:bxfby5g) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/disco.go#L23)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Could this be a flag.Duration type? https://golang.org/pkg/flag/#Duration
</blockquote></details>

Actually it can. I had tried to use `flag.Duration` in the past but it didn't make sense because `gocron` expected a `uint64` parameter. But now that `gocron` isn't being used, it now makes sense. Done.
___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA4M7n990icW5OTwO0V:b-8yd0oa) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Standardizing on one thing would be very welcome. It doesn't matter which one as long as the choice makes our lives easier.
</blockquote></details>

Standardization was the reasoning behind using `node`. We can't change the default k8s label `node` for things, but we do have control over our own labels. I don't expect that this one change will actually make our lives easier. Indeed there is a possibility that it could make our lives a touch more difficult if we find ourselves needing to join these metrics with metrics from, say, blackbox_exporter. But perhaps that pain, if we come to it, will cause us to start doing things to fix on using `node` instead of `machine` instead of fighting k8s.
___
*[metrics/metrics.go, line 41 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3cXOn2UC8h3ZEr1H5:-MA4Jn_K-b4EaSSe6dnp:b-2v0jej) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L41)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: why is this field named `intervalSeries`? is there a shorter name?
</blockquote></details>

My intention was to convey in the name that it was a series of samples taken during a write interval. Would you prefer something more generic like just `series`?
___
*[metrics/metrics.go, line 152 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3TzIrCyejiD8NfbSu:-MA4WvlG8Z7ntiPn7ALW:b-3azq05) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L152)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think I understand what the problem is.

The `metrics.oid` type is `map[string]oid` The value type is a struct literal. When getting a value from a map or returned from a function, the value is a _copy_. So, if you've observed that this doesn't work:

```
metrics.oids[oid].previousValue = value
```

It's because `previousValue` is being assigned to a temporary copy of the struct returned by the map lookup. 

To solve this, you can make the type a `map[string]*oid`. And, in `New` create the oid just as you're doing, but assign the `&oid{...}`. The return value of the map will still be a copy of the pointer, but because Go dereferences the pointer, there is only one version of the actual struct that the "pointer copy" points to. And, the assignment expression above should wai.
</blockquote></details>

Thank you for this explanation. I maybe _somewhat_ understood the nature of the issue, but not 100%, and this helps me to fully understand it, and fix it. I've implemented your suggestion and it works.
___
*[metrics/metrics.go, line 160 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3hW0h32rJi-5PmoUz:-MA4Khx74NDcGy4y2nAi:b-i0zk3t) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L160)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Because this is a bool, you can use variable without the comparison, (same below) i.e.

```
if metrics.firstRun {
  ...
}
```
</blockquote></details>

Good point. Updated.
___
*[metrics/metrics.go, line 198 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3e7b5C9mlxbrlNHWl:-MA4L1__9gPacJLJ_AEN:bmy09lr) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L198)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this add newlines between values? I'm also wondering whether `MustMarshalJSON` should use `MarshalIndent` rather than just `Marshal`? Don't do anything in this PR. This could be part of an "integration review".
</blockquote></details>

The code already does use `MarshalIndent`: https://github.com/m-lab/disco/blob/sandbox-kinkade/archive/archive.go#L33. I've noticed that DISCOv1 does not, but chose to use indenting for debugging and human readability, at the expense of each file being a handful of bytes larger.

No, the `append()` does not add newlines, which makes the output just _slightly_ different from DISCOv1 output.  The output of this utility currently looks like:

```
            "value": 368
        }
    ]
}{
    "experiment": "s1-lga0t.measurement-lab.org",
    "hostname": "mlab2.lga0t.mlab-sandbox.measurement-lab.org",
    "metric": "switch.unicast.uplink.tx",
```

... whereas the content of DISCOv1 would look like:

```
            "value": 368
        }
    ]
}
{
    "experiment": "s1-lga0t.measurement-lab.org",
    "hostname": "mlab2.lga0t.mlab-sandbox.measurement-lab.org",
    "metric": "switch.unicast.uplink.tx",
```

Subtle difference, but it's there. It was such a small difference that didn't affect readability that I chose to ignore it.

Regarding `MarshalIndent`
___
*[metrics/metrics.go, line 200 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3V0YXCfzYF9Mx6TR6:-MA4X8Lu9mGLxSI_Opjt:biiiu6i) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L200)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If the `metrics.oids` type is updated, this should solve this issue too.

Please add a comment that this is resetting the samples.
</blockquote></details>

This works. Thanks. And comment added.
___
*[metrics/metrics_test.go, line 396 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3j3J29kkYjZZCwRPj:-MA4NAKRDkovqhAj_pVG:bcxywbu) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics_test.go#L396)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to check the file contents?
</blockquote></details>

It could. I chose not to here, because writing file contents is the responsibility of the `archive` package and it didn't seem right to be testing the functionality of another package in this package's tests. The `archive` package [already has a test](https://github.com/m-lab/disco/blob/sandbox-kinkade/archive/archive_test.go#L110) to be sure that what is written is what is expected.

Is it more appropriate to test it here also?


<!-- Sent from Reviewable.io -->

2020-06-18 11:04 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA63rcR72w8cvDYsP6O:baabtpi) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Standardization was the reasoning behind using `node`. We can't change the default k8s label `node` for things, but we do have control over our own labels. I don't expect that this one change will actually make our lives easier. Indeed there is a possibility that it could make our lives a touch more difficult if we find ourselves needing to join these metrics with metrics from, say, blackbox_exporter. But perhaps that pain, if we come to it, will cause us to start doing things to fix on using `node` instead of `machine` instead of fighting k8s.
</blockquote></details>

Okay -- will k8s add the `node=` label automatically for this pod? My thinking to date (though under expressed and possibly incomplete) was to "explicitly add machine" and "allow k8s to automatically add node". That way we know which is which and there's no possibility of conflict, and we would normalize on the one that we control, since we have split prometheus clusters.

I expect that this `node` label will conflict with the automatic node label k8s service discovery adds to pods.
___
*[metrics/metrics.go, line 41 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3cXOn2UC8h3ZEr1H5:-MA65OUt6tW2IFY1wMDx:bcerfin) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L41)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

My intention was to convey in the name that it was a series of samples taken during a write interval. Would you prefer something more generic like just `series`?
</blockquote></details>

see below.
___
*[metrics/metrics.go, line 198 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3e7b5C9mlxbrlNHWl:-MA629t56-o6Z0Wi5LJx:b-hp0ao9) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L198)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The code already does use `MarshalIndent`: https://github.com/m-lab/disco/blob/sandbox-kinkade/archive/archive.go#L33. I've noticed that DISCOv1 does not, but chose to use indenting for debugging and human readability, at the expense of each file being a handful of bytes larger.

No, the `append()` does not add newlines, which makes the output just _slightly_ different from DISCOv1 output.  The output of this utility currently looks like:

```
            "value": 368
        }
    ]
}{
    "experiment": "s1-lga0t.measurement-lab.org",
    "hostname": "mlab2.lga0t.mlab-sandbox.measurement-lab.org",
    "metric": "switch.unicast.uplink.tx",
```

... whereas the content of DISCOv1 would look like:

```
            "value": 368
        }
    ]
}
{
    "experiment": "s1-lga0t.measurement-lab.org",
    "hostname": "mlab2.lga0t.mlab-sandbox.measurement-lab.org",
    "metric": "switch.unicast.uplink.tx",
```

Subtle difference, but it's there. It was such a small difference that didn't affect readability that I chose to ignore it.

Regarding `MarshalIndent`
</blockquote></details>

D'oh, I mixed up `MarshalIndent` and `Marshal` in my question. I saw that we were using `MarshalIndent`, but meant to wonder whether we should be using `Marshal` like DISCOv1 does. Also, DISCOv1 is formatted as JSONL -- I'm not sure if the back-to-back json qualifies as json or jsonl. I'm mostly worried about it being parsed the same way.
___
*[metrics/metrics.go, line 164 at r3](https://reviewable.io/reviews/m-lab/disco/3#-MA61giK7X0ajxYVP_SE:-MA61giK7X0ajxYVP_SF:b-mrq5ub) ([raw file](https://github.com/m-lab/disco/blob/ff5bb4be7f1a1a940756acf57c7126b1a3f85c38/metrics/metrics.go#L164)):*
> ```Go
> 		metrics.prom[metricName].WithLabelValues(metrics.hostname, ifDescr).Add(float64(increase))
> 
> 		metrics.oids[oid].intervalSeries.Samples = append(
> ```

`interval` would read easily here: `metrcis.oids[oid].interval.Samples = ...`
___
*[metrics/metrics_test.go, line 396 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3j3J29kkYjZZCwRPj:-MA62voa6b8_s1bHFPSQ:b-19m87t) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics_test.go#L396)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It could. I chose not to here, because writing file contents is the responsibility of the `archive` package and it didn't seem right to be testing the functionality of another package in this package's tests. The `archive` package [already has a test](https://github.com/m-lab/disco/blob/sandbox-kinkade/archive/archive_test.go#L110) to be sure that what is written is what is expected.

Is it more appropriate to test it here also?
</blockquote></details>

No, that's a fair objection. I don't see a parse/unmarshal in the archive tests either though. I do believe that one of either the archive package or this package should verify the data is parsable e2e. This is part of my concern about the output format / JSON/ JSONL comment above. The archive test has a single json object and does not unmarshal it. I think we need to see somewhere: multi-object JSON file unmarshalled.


<!-- Sent from Reviewable.io -->

2020-06-18 18:42 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA7POHwCwjtblB9vjHI:buuvt8o) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Okay -- will k8s add the `node=` label automatically for this pod? My thinking to date (though under expressed and possibly incomplete) was to "explicitly add machine" and "allow k8s to automatically add node". That way we know which is which and there's no possibility of conflict, and we would normalize on the one that we control, since we have split prometheus clusters.

I expect that this `node` label will conflict with the automatic node label k8s service discovery adds to pods.
</blockquote></details>

Ah, I had not considered that this label might collide with the label that auto-discovery might apply. I've changed this to machine, and we can see what happens.
___
*[metrics/metrics.go, line 41 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3cXOn2UC8h3ZEr1H5:-MA78le8C1vucjjEV-70:b-7b0beq) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L41)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

see below.
</blockquote></details>

Changed to `interval`, per your suggestion, which I like.
___
*[metrics/metrics.go, line 149 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3QTFX4L3pAwbguba7:-MA7jARJ5-AAq9GrkIg9:b-ad5jrs) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L149)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

For another TODO, it would be worth while collecting a prometheus metric for the collect time as well. Probably a histogram.
</blockquote></details>

It turned out to be quite easy to add this, so rather than a TODO, I just did it.  I also went ahead and got rid of the TODO above for counting errors and added that metric too.
___
*[metrics/metrics.go, line 198 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3e7b5C9mlxbrlNHWl:-MA7Lx6R9GlW2ygQk-xq:b-ltxpij) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L198)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

D'oh, I mixed up `MarshalIndent` and `Marshal` in my question. I saw that we were using `MarshalIndent`, but meant to wonder whether we should be using `Marshal` like DISCOv1 does. Also, DISCOv1 is formatted as JSONL -- I'm not sure if the back-to-back json qualifies as json or jsonl. I'm mostly worried about it being parsed the same way.
</blockquote></details>

The current output of DISCOv2 is definitely not JSONL, at least as I understand it.  It looks like the current DISCO parser reads in the data from the test file as a byte slice, then creates a new JSON decoder with that data as input, then iterates over it with `dec.More()`. From [the one-sentence description of `More()`](https://golang.org/pkg/encoding/json/#Decoder.More) it doesn't _appear_ that it is line based, but instead element based.

One question I do have is the current output of both DISCOv1 and DISCOv2 looks like:

```
{
   <data>
}
}
  <data>
}
[...]
```

I'm used to seeing arrays wrapped in square brackets. For a construct like the above is an array of object implied in the absence of surrounding `[ ]`?
___
*[metrics/metrics.go, line 164 at r3](https://reviewable.io/reviews/m-lab/disco/3#-MA61giK7X0ajxYVP_SE:-MA78DlO6MWjx9FjSv2X:bvxwqn8) ([raw file](https://github.com/m-lab/disco/blob/ff5bb4be7f1a1a940756acf57c7126b1a3f85c38/metrics/metrics.go#L164)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`interval` would read easily here: `metrcis.oids[oid].interval.Samples = ...`
</blockquote></details>

I like it. Changed.
___
*[metrics/metrics_test.go, line 396 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3j3J29kkYjZZCwRPj:-MA7QHs55VJvDLrGdi5D:b49n5x0) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics_test.go#L396)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

No, that's a fair objection. I don't see a parse/unmarshal in the archive tests either though. I do believe that one of either the archive package or this package should verify the data is parsable e2e. This is part of my concern about the output format / JSON/ JSONL comment above. The archive test has a single json object and does not unmarshal it. I think we need to see somewhere: multi-object JSON file unmarshalled.
</blockquote></details>

Okay, I didn't understand from your original comment that you were also concerned about being able to unmarshal the JSON, only that the file content was the expected content. 

Nowhere in this current code does unmarshaling JSON happen.  The JSON output is the direct result of `json.Marshal`. Does it need to be tested that the output of `json.Marshal` can actually be unmarshalled back into the original struct? It seem that that is a test of `json.Marshal` more than this code?

Would it satisfy your concern if  DISCOv2 just output the data in precisely the same way as DISCOv1? No indent, one record/element per line?


<!-- Sent from Reviewable.io -->

2020-06-18 19:06 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA7meKH1_zyVX3Q4Ob_:bv7m57g) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Ah, I had not considered that this label might collide with the label that auto-discovery might apply. I've changed this to machine, and we can see what happens.
</blockquote></details>

I wasn't actually thinking about k8s when I made my original comment. I'm inclined to suggest that the "machine" label should just be removed now, since we get the equivalent for free from k8s. And, there's no scenario that I can imagine where this value and the node value would not match. (this is a thorny issue, so not claiming i'm right).
___
*[metrics/metrics.go, line 198 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3e7b5C9mlxbrlNHWl:-MA7lV1H1bqKf8C80qTP:bzcqkcp) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L198)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The current output of DISCOv2 is definitely not JSONL, at least as I understand it.  It looks like the current DISCO parser reads in the data from the test file as a byte slice, then creates a new JSON decoder with that data as input, then iterates over it with `dec.More()`. From [the one-sentence description of `More()`](https://golang.org/pkg/encoding/json/#Decoder.More) it doesn't _appear_ that it is line based, but instead element based.

One question I do have is the current output of both DISCOv1 and DISCOv2 looks like:

```
{
   <data>
}
}
  <data>
}
[...]
```

I'm used to seeing arrays wrapped in square brackets. For a construct like the above is an array of object implied in the absence of surrounding `[ ]`?
</blockquote></details>

I don't _think_ there is an implied array. JSON arrays have very explicit structures that arenot in a JSONL file. 

The v1 output format is JSONL (iirc) -- it appears that was before I knew that term b/c the files are named ".json" which is a mistake. So, we have a decision. Either preserve the same behavior (meh) or "do the right thing". I think the right thing here is JSONL. I'm pretty sure we want a unit test to parse the output to verify it is parsable.
___
*[metrics/metrics_test.go, line 396 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3j3J29kkYjZZCwRPj:-MA7n_g80iW7F_V9oAsw:bsfelmf) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics_test.go#L396)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Okay, I didn't understand from your original comment that you were also concerned about being able to unmarshal the JSON, only that the file content was the expected content. 

Nowhere in this current code does unmarshaling JSON happen.  The JSON output is the direct result of `json.Marshal`. Does it need to be tested that the output of `json.Marshal` can actually be unmarshalled back into the original struct? It seem that that is a test of `json.Marshal` more than this code?

Would it satisfy your concern if  DISCOv2 just output the data in precisely the same way as DISCOv1? No indent, one record/element per line?
</blockquote></details>

It might be enough to write out in the same format as v1. How will the unit test verify that it has?


<!-- Sent from Reviewable.io -->

2020-06-18 20:41 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics/metrics.go, line 255 at r1](https://reviewable.io/reviews/m-lab/disco/3#-MA30Dpi1TX9XPtnTkC4:-MA7xyqG7-V4Tvh3yM-y:biztxxp) ([raw file](https://github.com/m-lab/disco/blob/80434fce58618756dbf93031c63be859ea27effe/metrics/metrics.go#L255)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I wasn't actually thinking about k8s when I made my original comment. I'm inclined to suggest that the "machine" label should just be removed now, since we get the equivalent for free from k8s. And, there's no scenario that I can imagine where this value and the node value would not match. (this is a thorny issue, so not claiming i'm right).
</blockquote></details>

That sounds like an even better solution. I'll still get what I wanted (I believe), which is a `node` label without a `machine` label. Done.
___
*[metrics/metrics.go, line 198 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3e7b5C9mlxbrlNHWl:-MA7yTiz9DztFq3_UNcq:b-c3nall) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics.go#L198)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't _think_ there is an implied array. JSON arrays have very explicit structures that arenot in a JSONL file. 

The v1 output format is JSONL (iirc) -- it appears that was before I knew that term b/c the files are named ".json" which is a mistake. So, we have a decision. Either preserve the same behavior (meh) or "do the right thing". I think the right thing here is JSONL. I'm pretty sure we want a unit test to parse the output to verify it is parsable.
</blockquote></details>

Sounds good. I'll convert the output to JSONL, and will name the files with an extension of `.jsonl`.
___
*[metrics/metrics_test.go, line 396 at r2](https://reviewable.io/reviews/m-lab/disco/3#-MA3j3J29kkYjZZCwRPj:-MA88q5AE1OhDTXDwWto:byxytw7) ([raw file](https://github.com/m-lab/disco/blob/aa8c1cc5f818518d8fa37b1f07562b3ac90e5c9b/metrics/metrics_test.go#L396)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It might be enough to write out in the same format as v1. How will the unit test verify that it has?
</blockquote></details>

The output should now be JSONL. Additionally, I removed the validity check for whether the written JSON matches some literal string, and instead now  marshal a set of test Models, write the JSONL to a file, then read that file back into a new set of Models, then compare the two sets for deep equality. This should verity that marshaling is working, that correct JSONL is being written, and that the written JSONL can be unmarshalled back into valid models that matched the originals.  Even more, I try to use the exact same method for reading in JSONL that the parse uses. 


<!-- Sent from Reviewable.io -->

2020-06-18 21:09 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> -- two small changes. Good work!

> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3#-:-MA8Fwp98ADk4Juaj35W:bggt6p0)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[archive/archive_test.go, line 123 at r4](https://reviewable.io/reviews/m-lab/disco/3#-MA8DMVZB0-c3EI3bP9T:-MA8DMVZB0-c3EI3bP9U:b-3lulf2) ([raw file](https://github.com/m-lab/disco/blob/70358f994c53862eca792a1a9bfa376b9a10ba64/archive/archive_test.go#L123)):*
> ```Go
> 	testArchivePath := fmt.Sprintf("%v/%v", dir, archivePath)
> 
> 	err = Write(testArchivePath, jsonData)
> ```

please check err.
___
*[metrics/metrics.go, line 222 at r4](https://reviewable.io/reviews/m-lab/disco/3#-MA8ELjJ2dILzoDlXH_k:-MA8ELjJ2dILzoDlXH_l:b-y902p0) ([raw file](https://github.com/m-lab/disco/blob/70358f994c53862eca792a1a9bfa376b9a10ba64/metrics/metrics.go#L222)):*
> ```Go
> 
> 	m := &Metrics{
> 		collectDuration: promauto.NewHistogramVec(
> ```

I think these metrics belong at the package level not as elements of the Metrics type.


<!-- Sent from Reviewable.io -->

2020-06-18 21:30 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/disco/3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[archive/archive_test.go, line 123 at r4](https://reviewable.io/reviews/m-lab/disco/3#-MA8DMVZB0-c3EI3bP9T:-MA8HB5t4V9fbKGBrkNW:b-896fix) ([raw file](https://github.com/m-lab/disco/blob/70358f994c53862eca792a1a9bfa376b9a10ba64/archive/archive_test.go#L123)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

please check err.
</blockquote></details>

Done.
___
*[metrics/metrics.go, line 222 at r4](https://reviewable.io/reviews/m-lab/disco/3#-MA8ELjJ2dILzoDlXH_k:-MA8InMz3feU4GQfW4G4:b3w8pc2) ([raw file](https://github.com/m-lab/disco/blob/70358f994c53862eca792a1a9bfa376b9a10ba64/metrics/metrics.go#L222)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think these metrics belong at the package level not as elements of the Metrics type.
</blockquote></details>

I've now declared them as package global variables.


<!-- Sent from Reviewable.io -->

2020-06-18 21:30 UTC, merged